### ISSUE TITLE
Validation not case sensitive for JSON keys

### ISSUE THREAD

**Issue by drasko** [litixsoft/lx-mongodb#1]
Both `{"name" : ...}` and `{"Name": ...}` when Schema uses only capital "Name".

**Comment by 4kochi** [comment]
JSON schema is treating keys as case sensitive. When you send `{"name" : ...}` it will be ignored by the schema, because it only knows `{"Name": ...}`. Depending on the JSON schema validator you use one can define what should happen which such data.

**Comment by drasko** [comment]
@4kochi I saw that I was not clear enough (I typed in speed obviously).

SW should work as you described, and that is what I expected. However, there seems to be a bug, and both `{"name" : ...}` and `{"Name": ...}` are passing validation OK, even though for `{"name" : ...}` validation should fail (Schema is defined with ``{"Name" : ...}`, so capital 'N').

This is the bug I wanted to report, and it is vell described in the issue subject.

Please reopen the issue.

**Comment by 4kochi** [comment]
Maybe you can provide an example. But in JSON schema it is totally valid to send an object `{"name" : ...}` although in the schema `{"Name" : ...}` is defined. If `"Name"` is required, than it should return an error. The `"name"` is ignored. 

You can test this with this site: http://jsonschemalint.com/draft4/#

Choose the sample "Sample schema and valid document". If you then change `"bar": "a"` to `"Bar": "a"`, there will be no error.

**Comment by drasko** [comment]
Thanks, I will check and keep you posted.

My use case is that I have `{"Name" : ...}` in the Schema and it is required. However, sending `{"name" : ...}` via `curl` passes validation, when it should fail.

If both `"bar": "a"` and `"Bar": "a"` are passing validation, even though the Schema is `"Bar": "a"` - does that means that JSON Schema is not case sensitive?

**Comment by 4kochi** [comment]
JSON Schema is case sensitive. If `{"Name" : ...}` is required and you send `{"name" : ...}` then there should be an error. Can you please share your schema and data.

**Comment by drasko** [comment]
@4kochi Schema is here: https://github.com/Mainflux/mainflux-core-server/blob/master/app/models/deviceSchema.json and validaion code is here: https://github.com/Mainflux/mainflux-core-server/blob/master/app/controllers/devices.js#L44

Sending `"name"` via `curl` passes the validation and adds `"name" : ...` to my object (here: https://github.com/Mainflux/mainflux-core-server/blob/master/app/controllers/devices.js#L56), when it should actually initialize `"Name" : ...`

**Comment by 4kochi** [comment]
Ok, i found the problem. It was actually a problem with [lx-valid](https://github.com/litixsoft/lx-valid). The required array you used in your schema `"required": ["Name"]` was not supported yet. 

I released a new version `1.2.0` of `lx-valid`. Please check if its working now.

**Comment by drasko** [comment]
@4kochi good work!

I confirm that it works correctly now. Bug fixed.

Thanks!

**Comment by drasko** [comment]
One more question - what happens to non-required fields? They are not validated for being capital or lowercase, as I can see. Is this OK by the spec, or this has to be corrected also?

**Comment by drasko** [comment]
@4kochi I saw now that I opened the issue on the wrong project ;).

New issue opened here: https://github.com/litixsoft/lx-valid/issues/15
